# Netlify configuration file
[build]
  # Build command
  command = "pnpm run build"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

  # Install pnpm before building
  [build.environment]
    NODE_VERSION = "20"
    PNPM_VERSION = "8.15.0"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
